
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS criado_em     TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS atualizado_em TIMESTAMP NULL;

ALTER TABLE hoteis   ADD COLUMN IF NOT EXISTS criado_em     TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE hoteis   ADD COLUMN IF NOT EXISTS atualizado_em TIMESTAMP NULL;

ALTER TABLE quartos  ADD COLUMN IF NOT EXISTS criado_em     TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE quartos  ADD COLUMN IF NOT EXISTS atualizado_em TIMESTAMP NULL;

ALTER TABLE reservas ADD COLUMN IF NOT EXISTS criado_em     TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE reservas ADD COLUMN IF NOT EXISTS atualizado_em TIMESTAMP NULL;
ALTER TABLE reservas ADD COLUMN IF NOT EXISTS excluido_em   TIMESTAMP NULL;

CREATE INDEX IF NOT EXISTS ix_reservas_ativas ON reservas (id) WHERE excluido_em IS NULL;
